text={"Reggel felébredtem. Mit tegyek?":"Reggel felébredtem. Mit tegyek most?",
   "fogmosás":"fogmosás",
    "reggeli":"reggeli",
    "öltözés":"öltözés",
    "Elmegyek fogat mosni. Sikálom rendesen, ahogy kell!":"Elmegyek fogat mosni. Sikálom rendesen, ahogy kell!",
    "Kellene valamit enni! Anya csinált valamit? Nézzük meg!":"Kellene enni valamit! Anya csinált valamit? Nézzük meg!",
    "Kissé hűvös van, kellene valami ruha! \nFelveszek egy nadrágot, meg egy pólót.":"Kissé hűvös van. Kellene valami ruha!\nFelveszek egy nadrágot, meg egy pólót.",
    "számting":"something",
    "futás":"futás",
      }
